# Generated by Django 5.2.5 on 2025-08-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_actualprecipitation_dewpoint_humidity_pressure_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActualPrecipitation',
        ),
        migrations.DeleteModel(
            name='ProvidedActual',
        ),
    ]
